-- ==============================================================================
-- MK SERVIÇOS AUTOMOTIVOS — SUPABASE POSTGRESQL SCHEMA
-- Execute este script no SQL Editor do seu projeto Supabase (https://supabase.com)
-- ==============================================================================

-- 1. Tabela de Usuários Administrativos
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Clientes
CREATE TABLE IF NOT EXISTS public.clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela de Veículos
CREATE TABLE IF NOT EXISTS public.vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  year TEXT NOT NULL,
  plate TEXT NOT NULL,
  mileage TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabela de Agendamentos
CREATE TABLE IF NOT EXISTS public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  vehicle_id BIGINT NOT NULL REFERENCES public.vehicles(id) ON DELETE CASCADE,
  service TEXT NOT NULL,
  description TEXT,
  date DATE NOT NULL,
  time TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Solicitação recebida',
  cancellation_reason TEXT,
  cancelled_by TEXT,
  cancelled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabela de Histórico e Auditoria
CREATE TABLE IF NOT EXISTS public.appointment_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT NOT NULL REFERENCES public.appointments(id) ON DELETE CASCADE,
  previous_status TEXT,
  new_status TEXT,
  note TEXT NOT NULL,
  user_name TEXT NOT NULL DEFAULT 'Sistema',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Tabela de Expediente da Oficina
CREATE TABLE IF NOT EXISTS public.business_schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_of_week INT NOT NULL UNIQUE, -- 0=Domingo, 1=Segunda, ..., 6=Sábado
  day_name TEXT NOT NULL,
  open_time TEXT NOT NULL,
  close_time TEXT NOT NULL,
  lunch_start TEXT,
  lunch_end TEXT,
  slot_interval_minutes INT DEFAULT 60,
  is_active INT DEFAULT 1
);

-- 7. Tabela de Bloqueios Pontuais
CREATE TABLE IF NOT EXISTS public.blocked_slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  time TEXT,
  reason TEXT NOT NULL,
  created_by TEXT NOT NULL DEFAULT 'Administrador',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Tabela de Configurações da Oficina
CREATE TABLE IF NOT EXISTS public.workshop_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  description TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- SEED DE DADOS INICIAIS
-- ==============================================================================

-- Admin padrão: admin@mkservicos.com.br / admin123 (hash bcrypt)
INSERT INTO public.users (name, email, password_hash, role)
VALUES (
  'Administrador MK',
  'admin@mkservicos.com.br',
  '$2a$10$wJtK1P9Lz6.y2B2E9M6I9OB6H4m5PZ5Vv6D2XbQW2wE8jZ1R0o2iG',
  'admin'
)
ON CONFLICT (email) DO NOTHING;

-- Grade semanal padrão
INSERT INTO public.business_schedule (day_of_week, day_name, open_time, close_time, lunch_start, lunch_end, slot_interval_minutes, is_active)
VALUES
  (0, 'Domingo', '08:00', '12:00', NULL, NULL, 60, 0),
  (1, 'Segunda-feira', '08:00', '18:00', '12:00', '13:30', 60, 1),
  (2, 'Terça-feira', '08:00', '18:00', '12:00', '13:30', 60, 1),
  (3, 'Quarta-feira', '08:00', '18:00', '12:00', '13:30', 60, 1),
  (4, 'Quinta-feira', '08:00', '18:00', '12:00', '13:30', 60, 1),
  (5, 'Sexta-feira', '08:00', '18:00', '12:00', '13:30', 60, 1),
  (6, 'Sábado', '08:00', '12:00', NULL, NULL, 60, 1)
ON CONFLICT (day_of_week) DO NOTHING;

-- Configurações da oficina
INSERT INTO public.workshop_settings (key, value, description)
VALUES
  ('workshop_name', 'MK SERVIÇOS AUTOMOTIVOS', 'Nome oficial da oficina'),
  ('workshop_phone', '(11) 98878-7548', 'Telefone comercial'),
  ('workshop_whatsapp', '5511988787548', 'WhatsApp para atendimento'),
  ('workshop_email', 'mkservicosautomotivos5@gmail.com', 'E-mail de contato e notificações'),
  ('workshop_address', 'Rua O, 83 - Vitória Régia, SP', 'Endereço físico'),
  ('workshop_instagram', '@mk.automotivos', 'Perfil do Instagram'),
  ('workshop_maps_embed', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3658.0471206132333!2d-46.73236372467069!3d-23.530799778819515!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94cef892bf4bfbfb%3A0x2a0fefc2a9ec682b!2sRua%20O%2C%2083%20-%20Vitoria%20Regia%2C%20SP!5e0!3m2!1spt-BR!2sbr!4v1700000000000!5m2!1spt-BR!2sbr', 'URL iframe do Google Maps')
ON CONFLICT (key) DO NOTHING;

-- Desativar RLS para permitir que o backend com service_role ou anon acesse as tabelas
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointment_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_schedule DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocked_slots DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.workshop_settings DISABLE ROW LEVEL SECURITY;
